### ISSUE TITLE
Error on open

### ISSUE THREAD

**Issue by AlexByte** [reiryuki/Moto-Widget-and-Launcher-Magisk-Module#2]
Android 10 LineageOS 17.1
![Screenshot_20220802-174525912](https://user-images.githubusercontent.com/25251772/182403373-bfa313e7-6bb8-4317-ab1a-cb738f2c6b65.jpg)

[magisk_install_log_2022-08-02T171414Z.log](https://github.com/reiryuki/Moto-Launcher-Magisk-Module/files/9243255/magisk_install_log_2022-08-02T171414Z.log)
[logcat_08-02-2022_17-26-56.txt](https://github.com/reiryuki/Moto-Launcher-Magisk-Module/files/9243256/logcat_08-02-2022_17-26-56.txt)

[z.zip](https://github.com/reiryuki/Moto-Launcher-Magisk-Module/files/9243218/z.zip)

**Comment by reiryuki** [comment]
Not approved
Reason: Logcat size less than 1 MB

**Comment by AlexByte** [comment]
@reiryuki  Why do you need big logcat size? in this logcat file all the data about the moment when the error occurs.
