### ISSUE TITLE
Freezing on switcher, can we disabling the search bar on app drawer

### ISSUE THREAD

**Issue by shimabde** [reiryuki/Moto-Widget-and-Launcher-Magisk-Module#3]
![Screenshot_20230326-030557](https://user-images.githubusercontent.com/10106046/227739211-fcaf77eb-d92c-48c6-b1d7-27560d395ac2.png)

**Comment by reiryuki** [comment]
I will never support 'talking only' without sending proper logs. If you want a fix, then read #bug_report carefully, and send required files to the author.
